### ISSUE TITLE
Some improvements request

### ISSUE THREAD

**Issue by malomaster** [LukeKvamme/Coal-Expanded#1]
Hi.
I propose to make some improvements so that the conversion of coal into a denser fuel gives some profit. This is especially true when playing with bobmods.
Firstly, I suggest that each following recipe adds an energy bonus, and preferably increasing, for example, 5-10-15-20-25%, i.e. coal gives 4 MJ, Lignite — 42 MJ, Sub-Bituminous Coal — 464 MJ, Bituminous Coal — 5336 MJ, Anthracite — 64032 MJ, and Diamond — 800400 (rounded up to 800,000) MJ. Or, if this is too much, you can stop at 0-2.5-5-7.5-10%, i.e. 4 - 40 - 410 - 4305 - 46280 - 509080 MJ.
Secondly, if I'm not mistaken, bobmods makes coal have a 200% pollution coefficient. Therefore, I suggest that each subsequent variant of coal concentration had less pollution, for example, 200% (coal) - 150 - 120 - 100 - 85 - 75%. This will also greatly increase the attractiveness of denser fuel. Of course, you can completely accelerate and put pollution 200 - 150 - 100 - 75 - 50 - 25%, but, in my opinion, this will already be outright cheating.

**Comment by malomaster** [comment]
Hi.
I some edited and tweaked your mod, [here is the link](https://drive.google.com/file/d/1UwezmPel240TY_xxeZ-O58y6RFgiZkhV/view?usp=sharing). If you wanted, you can upload it on mods.factorio.com.

Changes:
1. Renamed all recipes and items to CE_[old_name] (now with "_" instead of " ") because of possible compatibility issues with other mods (first of all — "Diamond" item and|or recipe).
2. Added two settings — "Coal density energy bonus" and "Coal density speed bonus". The first option gives energy bonus for more dense coal-based types of fuel, also, if enabled "Bobpower" mod, every next dense coal-based fuel have lesser pollution and got 200 stack size instead of 100 (because "Bobpower" also increase coal stack size to 200). The second option give to all vehicles acceleration and maximum speed bonuses up to 200/150% from Diamond. I think, it's more or less fair and will not be considered as cheating fuel.
3. Make right recipe order Lignite --> Sub-Bit. coal --> Bit. coal --> Antracite --> Diamond (order z1-z5)
4. Updated icons (removed that nasty white background).
5. Updated EN and added RU localization.

**Comment by LukeKvamme** [comment]
Thanks so much for all the help! This is my first mod I've ever tried making and also my first time using Lua -- I've been pretty slow at completing the stuff you had mentioned the other day, so this was a big help. I tested everything, it all worked great, so I merged it and updated the mod. The effects should be there by now.
