### ISSUE TITLE
File not found lignite.png

### ISSUE THREAD

**Issue by blade2005** [LukeKvamme/Coal-Expanded#2]
Installed 0.2.0 can't load it due to this file not being found `__Coal-Expanded__/icons/lignite.png`

Edit: I suspect it's a capitalization issue. The repo file says `Lignite`

**Comment by LukeKvamme** [comment]
Yup, you were right about the capitalization issue. Thanks for letting me know, I was messing around yesterday trying to get rid of the white backgrounds and I think I accidentally renamed it in the process. It's fixed and updated now, ran it myself to make sure.
