### ISSUE TITLE
Stack Size

### ISSUE THREAD

**Issue by Tenderroast** [LukeKvamme/Coal-Expanded#6]
About the new stack size increase. Maybe put in an option in the startup mod settings, so the user can choose how big of an increase they want? if any at all

**Comment by LukeKvamme** [comment]
Hey Tenderroast, that is a good idea I had not considered. I'll try and implement that today.

**Comment by LukeKvamme** [comment]
Alright, it has been added. Setting toggles stack size for coal and coal variants on/off, by default it is off.
